### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by lunofe**
# parity
- replace "Fork: -" with "Fork: N/A"
- move colons inside bold formatting
- some other similar small adjustments

# fix copy and paste error?
seems like there's been an error, because the fork lineage does not include the final result
https://github.com/LeStegii/server-softwares/blob/c22d5bfcadb93105e85ce3b94685d8eb095eb588/java/FOLIA.md?plain=1#L35-L38

# move folia note up
instead of adding a footnote which users might not see with the list growing, the folia plugin compatability note now is at the top
image

### CODE REVIEW

**Review by LeStegii — COMMENTED** [review]
Thanks for all the fixes!
I'm not sure about the `N/A` for projects that aren't a fork of anything else.
Is there a special reason for chosing this instead of the old `-`?

**Comment by lunofe** [comment]
Personally, I think it looks a bit better, and it also leaves some more space for the meaning. N/A could mean there is none, _or_ that we don't know it / didn't add it yet. I'd interpret a single dash as _none_.

**Comment by LeStegii** [comment]
I see, but in most of the cases you added a N/A (e.g. with gate), there really is no fork chain as it isn't a fork.
I think we should somehow differeantiate between "no fork" and "fork chain unknown".

**Comment by lunofe** [comment]
found two more issues that need fixing before merge

**Pull request merged**
