### PR TITLE
Waterfall reached EOL

### PR DESCRIPTION
**Pull request by notTamion**
Waterfall has reached end of life and will no longer receive updates. There is currently 2 prs open on the paper website and docs repos to document this.

### CODE REVIEW

**Comment by LeStegii** [comment]
Thanks for your PR!
Didn't think this would happen but it was about time.

I think this can be merged as soon as the Paper PRs are confirmed (Maybe even earlier as electronicboy already confirmed the EOL state on discord.

**Review by LeStegii — CHANGES_REQUESTED** [review]
Changes itself look good, but since Waterfall is EOL it should be removed from all other things referencing it, such as "alternatives".

This might be out of scope for this PR, so maybe I'll do it myself tomorrow.

**Comment by notTamion** [comment]
i would say this is still in scope for the pr. though feel free to revert the commit if your feel otherwise

**Review by LeStegii — APPROVED** [review]

**Comment by LeStegii** [comment]
I readded Bungeecord as an alternative for outdated softwares descending from Bungeecord/Waterfall.
With this I also fixed some older mistakes I noticed in fork chains and such.

I just rechecked with the discord. It seems like Waterfall has been EOL for quite some time so I feel like merging this is okay.
grafik

**Pull request merged**
